#!/usr/bin/env spang2
# @endpoint spang
# @option -a
# @param tax=8090
# @input (ncbigene:30207)

PREFIX orth: <http://purl.org/net/orth#>
PREFIX taxid: <http://identifiers.org/taxonomy/>
PREFIX : <https://dbcls.github.io/ncbigene-rdf/ontology.ttl#>

SELECT DISTINCT ?gene2 ?label ?desciption
WHERE {
  VALUES (?gene1) { ${INPUT} }
  ?gene1 orth:hasOrtholog+ ?gene2 .
  ?gene1 :taxid taxid:7955 .
  ?gene2 :taxid taxid:${tax} .
  OPTIONAL {
    ?gene2 rdfs:label ?label .
  }
  OPTIONAL {
    ?gene2 dct:description ?desciption .
  }
}
